### ISSUE TITLE
Improve motivation in README

### ISSUE THREAD

**Issue by sgbaird** [deepanshs/csdmpy#29]
It would be nice to see (a bit more up-front) how `csdmpy` fits in-between the basic data format of a CSV (e.g. X-Y data) and the much more complex data format of [GEMD](https://citrineinformatics.github.io/gemd-docs/) geared towards handling information like sequential experimental processing data and metadata. As well as:

- Why would I want to use CSD as opposed to a CSV, JPG, etc.?
- Who else has used this so far and to what end? (esp. citing publications)

Btw, nice documentation and nice package!

**Comment by deepanshs** [comment]
Hi @sgbaird. Thanks for checking the `csdmpy` package and documentation. You are correct; the readme page could use more description. Some of your questions are addressed in our [PLOS ONE publication](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0225953). I will include those in the readme.

Regarding the GEMD format, do you have any specific questions? I am not familiar with this format. Correct me if I am wrong, but GEMD seems like a data workflow format. The CSDM data format is designed for serializing multi-dimensional scientific datasets with metadata.
