### ISSUE TITLE
Error when saving CSDM objects

### ISSUE THREAD

**Issue by mccarthy677** [deepanshs/csdmpy#42]
When I create a csdm object, I can save it with no issues.  When I try to change the csdm object, by replacing scaling a dimension or replacing a dimension, the object then will not save

Exact error message: "TypeError: Object of type PhysicalType is not JSON serializable"

Windows, python 3.9.7, csdmpy 0.4.1

**Comment by deepanshs** [comment]
@mccarthy677 For log purposes, can you also provide a code snippet for reproducing the bug?

**Comment by mccarthy677** [comment]
Code snippet (starting from saving the csdm object from an mrsimulator simulation):

```
data = sim.methods[0].simulation  # extract the response
d0, d1 = data.x[0], data.x[1]  # extract the coordinates
dv = data.y[0] # extract the dependent variable

new_d0 = d0/2 #update one dimension

newobj = cp.CSDM(dimensions=[new_d0,d1], dependent_variables=[dv]) #build new object

newobj.save("test.csdf") # save object
```
